# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cd4fabe0944004678b5672e78ec158945a0f5ac0c2ff158a1e723b022650e96633b08a8d364e362ffdb2f471adb5fc397e32eb0359c4186d0506704bcefd3c3b

test:
  secret_key_base: 6ea47e65623605e67cb7e6478a3348d758e20c6419c1291646dfe00c644497e19dd9eafa4df3665631858e89c73651b04fec6973ad111a93bf51ed83e5fa1fb2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
